#pragma once

#define DEFAULT_MSG_TEXTSIZE 50
#define DEFAULT_MSG_ESSENTIALBYTES 21
#define DEFAULT_MSG_NONESSENTIALBYTES 36
#define DEFAULT_MSGSIZE (DEFAULT_MSG_ESSENTIALBYTES + DEFAULT_MSG_NONESSENTIALBYTES + DEFAULT_MSG_TEXTSIZE)
#define DEFAULT_CHATSIZE (DEFAULT_MSGSIZE - DEFAULT_MSG_ESSENTIALBYTES)

#include "Enums.h"
#include "Coord.h"

enum MSGTYPE {
	MSGTYPE_NONE,
	MSGTYPE_MOVE,
	MSGTYPE_ACTION,
	MSGTYPE_SOUND,
	MSGTYPE_INQUIRY,
	MSGTYPE_JOIN,
	MSGTYPE_LEAVE,
	MSGTYPE_RESYNCGAME,
	MSGTYPE_SELECT,
	MSGTYPE_NEXTTURN,
	MSGTYPE_LOAD,
	MSGTYPE_DONELOAD,
	MSGTYPE_AISTEP,
	MSGTYPE_INFO,
	MSGTYPE_CLEAR,
	MSGTYPE_CONNECT,
	MSGTYPE_DISCONNECT,
	MSGTYPE_TEXT,
	MSGTYPE_GAMECONFIG,
	MSGTYPE_LOGIN,
	MSGTYPE_CREATEUSER,
	MSGTYPE_ERROR,
	MSGTYPE_PLACEPROG,
	MSGTYPE_CHAT,
	MSGTYPE_PROGINVENTORY,
	MSGTYPE_CREDITPICKUP,
	MSGTYPE_LEVELUNLOCK
};

enum MSGSOUNDNAME {
	MSGSOUNDNAME_MOVE,
	MSGSOUNDNAME_DAMAGE,
	MSGSOUNDNAME_HEAL,
	MSGSOUNDNAME_ZERO,
	MSGSOUNDNAME_ONE,
	MSGSOUNDNAME_SIZEMOD,
	MSGSOUNDNAME_SPEEDMOD,
	MSGSOUNDNAME_PICKUPCREDIT
};

enum MSGINQUIRYTYPE {
	MSGINQUIRYTYPE_TILECONTENTS,
	MSGINQUIRYTYPE_SELECTEDTILE,
	MSGINQUIRYTYPE_SELECTEDPROG
};

enum MSGSELECTTYPE {
	MSGSELECTTYPE_PROGRAM,
	MSGSELECTTYPE_TILE,
	MSGSELECTTYPE_ACTION
};

enum MSGLEVELTYPE {
	MSGLEVELTYPE_LOAD,
	MSGLEVELTYPE_SAVE,
	MSGLEVELTYPE_CLEAR
};

enum MSGINFOTYPE {
	MSGINFOTYPE_TILE,
	MSGINFOTYPE_BKG,
	MSGINFOTYPE_ITEM,
	MSGINFOTYPE_ACTION,
	MSGINFOTYPE_GAMESTATUS,
	MSGINFOTYPE_USERNAME,
	MSGINFOTYPE_PASSWORD,
	MSGINFOTYPE_PROGINVENTORY,
	MSGINFOTYPE_CREDITS,
	MSGINFOTYPE_ANIM,

	// entity creation
	MSGINFOTYPE_TEAM,
	MSGINFOTYPE_PLAYER,
	MSGINFOTYPE_PROGRAM,

	// entity deletion
	MSGINFOTYPE_TEAMDELETE,
	MSGINFOTYPE_PLAYERDELETE,
	MSGINFOTYPE_PROGRAMDELETE,

	// program modification
	MSGINFOTYPE_PROGRAMADDTAIL,
	MSGINFOTYPE_PROGRAMADDHEAD,
	MSGINFOTYPE_PROGRAMREMOVETILE,
	MSGINFOTYPE_PROGRAMCHANGENUMACTIONS,
	MSGINFOTYPE_PROGRAMCHANGENUMMOVES,
	MSGINFOTYPE_PROGRAMCHANGEMAXHEALTH,
	MSGINFOTYPE_PROGRAMCHANGEMAXACTIONS,
	MSGINFOTYPE_PROGRAMCHANGEMAXMOVES
};

enum MSGGAMECONFIGTYPE {
	MSGGAMECONFIGTYPE_FFA,
	MSGGAMECONFIGTYPE_TEAMDM,
	MSGGAMECONFIGTYPE_COOP
};

struct Message {
	// message type
	MSGTYPE type;

	// ids
	int clientID;
	int teamID;
	int playerID;
	int programID;
	int actionID;

	// general-use position fields
	Coord pos;
	Coord pos2;

	// general-purpose ints
	int num;
	int num2;

	// select
	MSGSELECTTYPE selectType;

	// sound
	MSGSOUNDNAME soundType;

	// level load
	MSGLEVELTYPE levelType;

	// inquiry
	MSGINQUIRYTYPE inquiryType;

	// info
	MSGINFOTYPE infoType;
	GAMESTATUS statusType;
	TILE tileType;
	BACKGROUND bkgType;
	PROGRAM progType;
	ITEM itemType;
	ANIMTYPE animType;

	// game config
	MSGGAMECONFIGTYPE gameConfigType;

	// text
	char text[DEFAULT_MSGSIZE];
};

void _serializeMessage(char* buffer, Message m);

Message _deserializeMessage(char* in);

void _printMessage(Message m);