#ifndef ENUMS_H
#define ENUMS_H

enum PROGRAM
{
    // special numerations
    PROGRAM_NONE = 0,
    PROGRAM_CUSTOM,

    // player programs
    PROGRAM_BALLISTA,
    PROGRAM_BITMAN,
    PROGRAM_BITMAN2,
    PROGRAM_BLACKWIDOW,
    PROGRAM_BUG,
    PROGRAM_BUG2,
    PROGRAM_BUG3,
    PROGRAM_CATAPULT,
    PROGRAM_CLOG,
    PROGRAM_CLOG2,
    PROGRAM_CLOG3,
    PROGRAM_DATABOMB,
    PROGRAM_DATADOCTOR,
    PROGRAM_DATADOCTOR2,
    PROGRAM_FIDDLE,
    PROGRAM_GOLEM,
    PROGRAM_GOLEM2,
    PROGRAM_GOLEM3,
    PROGRAM_HACK,
    PROGRAM_HACK2,
    PROGRAM_HACK3,
    PROGRAM_KAMIKAZEE,
    PROGRAM_MEDIC,
    PROGRAM_MEMHOG,
    PROGRAM_MOBILETOWER,
    PROGRAM_SATELLITE,
    PROGRAM_SATELLITE2,
    PROGRAM_SEEKER,
    PROGRAM_SEEKER2,
    PROGRAM_SEEKER3,
    PROGRAM_SLINGSHOT,
    PROGRAM_SPECS,
    PROGRAM_SUMO,
    PROGRAM_TARANTULA,
    PROGRAM_TOWER,
    PROGRAM_TURBO,
    PROGRAM_TURBO2,
    PROGRAM_TURBO3,
    PROGRAM_WIZARD,
    PROGRAM_WOLFSPIDER,

    // enemy programs
    PROGRAM_BOSS,
    PROGRAM_DOG,
    PROGRAM_DOG2,
    PROGRAM_DOG3,
    PROGRAM_FIREWALL,
    PROGRAM_SONAR,
    PROGRAM_SONAR2,
    PROGRAM_SONAR3,
    PROGRAM_WALKER,
    PROGRAM_WALKER2,
    PROGRAM_WALKER3,
    PROGRAM_WARDEN,
    PROGRAM_WARDEN2,
    PROGRAM_WARDEN3,
    PROGRAM_WATCHMAN,
    PROGRAM_WATCHMAN2,
    PROGRAM_WATCHMAN3,

    // number of programs
    PROGRAM_NUM_PROGTYPES
};

enum ITEM
{
    ITEM_NONE = 0,
    ITEM_CREDIT,
    ITEM_BIGCREDIT,
    ITEM_FILES,
    ITEM_NUM_ITEMS
};

enum TILE
{
    TILE_NONE = 0,
    TILE_PLAIN,
    TILE_PLAIN2,
    TILE_PLAIN3,
    TILE_PLAIN4,
    TILE_PLAIN5,
    TILE_PLAIN6,
    TILE_PLAIN7,
    TILE_PLAIN8,
    TILE_PLAIN9,
    TILE_SPAWN,
    TILE_SPAWN2,
    TILE_NUM_TILES
};

enum BRUSH
{
    BRUSH_NONE = 0,
    BRUSH_TILES,
    BRUSH_PROGRAMS,
    BRUSH_DELETEPROGRAMS,
    BRUSH_ITEMS,
    BRUSH_NUM_BRUSHES
};

enum MOVE
{
    MOVE_NONE = 0,
    MOVE_DAMAGE,
    MOVE_HEAL,
    MOVE_SPEEDUP,
    MOVE_SPEEDDOWN,
    MOVE_MAXHEALTHUP,
    MOVE_MAXHEALTHDOWN,
    MOVE_TILEPLACE,
    MOVE_TILEDELETE,
    MOVE_NUM_MOVES
};

enum BACKGROUND
{
    BKG_NONE = 0,
    BKG_DONUT,
    BKG_PHARM,
    BKG_MONKEY,
    BKG_CELL,
    BKG_PED,
    BKG_NUM_BKGS
};

#endif
