#ifndef ENUMS_H
#define ENUMS_H

enum NODESTATUS
{
    NODESTATUS_HIDDEN = 0,
    NODESTATUS_UNOWNED,
    NODESTATUS_UNOWNED_SELECTED,
    NODESTATUS_OWNED,
    NODESTATUS_OWNED_SELECTED
};

enum PROGRAM
{
    // special numerations
    PROGRAM_NONE = 0,
    PROGRAM_CUSTOM,

    // player programs
    PROGRAM_BALLISTA,
    PROGRAM_BITMAN,
    PROGRAM_BITMAN2,
    PROGRAM_BLACKWIDOW,
    PROGRAM_BUG,
    PROGRAM_BUG2,
    PROGRAM_BUG3,
    PROGRAM_CATAPULT,
    PROGRAM_CLOG,
    PROGRAM_CLOG2,
    PROGRAM_CLOG3,
    PROGRAM_DATABOMB,
    PROGRAM_DATADOCTOR,
    PROGRAM_DATADOCTOR2,
    PROGRAM_FIDDLE,
    PROGRAM_GOLEM,
    PROGRAM_GOLEM2,
    PROGRAM_GOLEM3,
    PROGRAM_HACK,
    PROGRAM_HACK2,
    PROGRAM_HACK3,
    PROGRAM_KAMIKAZEE,
    PROGRAM_MEDIC,
    PROGRAM_MEMHOG,
    PROGRAM_MOBILETOWER,
    PROGRAM_SATELLITE,
    PROGRAM_SATELLITE2,
    PROGRAM_SEEKER,
    PROGRAM_SEEKER2,
    PROGRAM_SEEKER3,
    PROGRAM_SLINGSHOT,
    PROGRAM_SPECS,
    PROGRAM_SUMO,
    PROGRAM_TARANTULA,
    PROGRAM_TOWER,
    PROGRAM_TURBO,
    PROGRAM_TURBO2,
    PROGRAM_TURBO3,
    PROGRAM_WIZARD,
    PROGRAM_WOLFSPIDER,

    // enemy programs
    PROGRAM_BOSS,
    PROGRAM_DOG,
    PROGRAM_DOG2,
    PROGRAM_DOG3,
    PROGRAM_FIREWALL,
    PROGRAM_SONAR,
    PROGRAM_SONAR2,
    PROGRAM_SONAR3,
    PROGRAM_WALKER,
    PROGRAM_WALKER2,
    PROGRAM_WALKER3,
    PROGRAM_WARDEN,
    PROGRAM_WARDEN2,
    PROGRAM_WARDEN3,
    PROGRAM_WATCHMAN,
    PROGRAM_WATCHMAN2,
    PROGRAM_WATCHMAN3,

    // number of programs
    PROGRAM_NUM_PROGTYPES
};

enum ITEM
{
    ITEM_NONE = 0,
    ITEM_CREDIT,
    ITEM_BIGCREDIT,
    ITEM_FILES,
    ITEM_NUM_ITEMS
};

enum TILE
{
    TILE_NONE = 0,
    TILE_PLAIN,
    TILE_PLAIN2,
    TILE_PLAIN3,
    TILE_PLAIN4,
    TILE_PLAIN5,
    TILE_PLAIN6,
    TILE_PLAIN7,
    TILE_PLAIN8,
    TILE_PLAIN9,
    TILE_SPAWN,
    TILE_SPAWN2,
    TILE_NUM_TILES
};

enum BRUSH
{
    BRUSH_NONE = 0,
    BRUSH_TILES,
    BRUSH_PROGRAMS,
    BRUSH_DELETEPROGRAMS,
    BRUSH_ITEMS,
    BRUSH_NUM_BRUSHES
};

enum MOVETYPE
{
    MOVETYPE_NONE = 0,
    MOVETYPE_DAMAGE,
    MOVETYPE_HEAL,
    MOVETYPE_SPEEDUP,
    MOVETYPE_SPEEDDOWN,
    MOVETYPE_MAXHEALTHUP,
    MOVETYPE_MAXHEALTHDOWN,
    MOVETYPE_TILEPLACE,
    MOVETYPE_TILEDELETE,
    MOVETYPE_NUM_MOVETYPES
};

enum BACKGROUND
{
    BKG_NONE = 0,
    BKG_DONUT,
    BKG_PHARM,
    BKG_MONKEY,
    BKG_CELL,
    BKG_PED,
    BKG_NUM_BKGS
};

enum ANCHOR
{
    ANCHOR_NORTHWEST,
    ANCHOR_NORTH,
    ANCHOR_NORTHEAST,
    ANCHOR_EAST,
    ANCHOR_SOUTHEAST,
    ANCHOR_SOUTH,
    ANCHOR_SOUTHWEST,
    ANCHOR_WEST,
    ANCHOR_CENTER
};

enum FONT
{
    FONT_NORMAL,
    FONT_BOLD
};

enum CAMPAIGN
{
    CAMPAIGN_CLASSIC,
    CAMPAIGN_NIGHTFALL,
    CAMPAIGN_CUSTOM
};

enum GAMESTATUS
{
    GAMESTATUS_NO_GAME,
    GAMESTATUS_PLACING_PROGRAMS,
    GAMESTATUS_PLAYING,
    GAMESTATUS_WON,
    GAMESTATUS_LOST
};

enum DEBUG
{
    DEBUG_NONE = 0,
    DEBUG_MINIMAL,
    DEBUG_NORMAL,
    DEBUG_EXTRA
};

enum MOVEPRESET
{
    MOVEPRESET_MEGAGROW,
    MOVEPRESET_GROW,
    MOVEPRESET_SLICE,
    MOVEPRESET_DATASLAM,
    MOVEPRESET_STING,
    MOVEPRESET_KAMIKAZEE,
    MOVEPRESET_ZERO,
    MOVEPRESET_ONE,
    MOVEPRESET_STONE,
    MOVEPRESET_POKE,
    MOVEPRESET_SEEK_AND_DESTROY,
    MOVEPRESET_TWIDDLE,
    MOVEPRESET_TWEAK,
    MOVEPRESET_TASER,
    MOVEPRESET_MEGABYTE,
    MOVEPRESET_CUT,
    MOVEPRESET_PONG,
    MOVEPRESET_BLIP,
    MOVEPRESET_ZAP,
    MOVEPRESET_FRY,
    MOVEPRESET_PEEK,
    MOVEPRESET_MUTILATE,
    MOVEPRESET_DICE,
    MOVEPRESET_GLITCH,
    MOVEPRESET_FRACTAL_GLITCH,
    MOVEPRESET_QUANTUM_GLITCH,
    MOVEPRESET_BASH,
    MOVEPRESET_CRASH,
    MOVEPRESET_LAUNCH,
    MOVEPRESET_SCRAMBLE,
    MOVEPRESET_FLING,
    MOVEPRESET_HYPO,
    MOVEPRESET_BURN,
    MOVEPRESET_LAG,
    MOVEPRESET_CHUG,
    MOVEPRESET_HANG,
    MOVEPRESET_BOOST,
    MOVEPRESET_MEGABOOST,
    MOVEPRESET_FIRE,
    MOVEPRESET_ICE,
    MOVEPRESET_SCORCH,
    MOVEPRESET_STRETCH,
    MOVEPRESET_PHASER,
    MOVEPRESET_BYTE,
    MOVEPRESET_DARKSTORM,
    MOVEPRESET_FLASHGROW,
    MOVEPRESET_OVERCLOCK,
    MOVEPRESET_CRUNCHTIME,
    MOVEPRESET_PING,
    MOVEPRESET_PHOTON,
    MOVEPRESET_THUMP,
    MOVEPRESET_PARALYZE,
    MOVEPRESET_SELFDESTRUCT,
    MOVEPRESET_MEGASCRAMBLE,
    MOVEPRESET_SHUTDOWN,
    MOVEPRESET_SURGERY,
    MOVEPRESET_CONSTRUCTOR,
    MOVEPRESET_DECONSTRUCTOR,
    MOVEPRESET_GIGABOOST,

    MOVEPRESET_NUM_MOVEPRESETS,
    MOVEPRESET_CUSTOM
};

#endif
